### PR TITLE
chore: Bump backstage to 1.8.2

### PR DESCRIPTION
**Pull request by SamoKopecky**
Release notes: https://github.com/backstage/backstage/releases/tag/v1.8.0
Upgrade helper: https://backstage.github.io/upgrade-helper/?from=1.7.0&to=1.8.2

## Changes
- Move support of `node` to 16 and 18
- Remove Google Analytics tracking
- Shuffle some imports to use new components
- Split `build` command into `build:all` and `build:backend`

### CODE REVIEW

**Comment by tumido** [comment]
/hold

We can't do this as of now. We don't have an UBI based nodejs v18 image available without auth yet. https://bugzilla.redhat.com/show_bug.cgi?id=2092958

**Comment by SamoKopecky** [comment]
> /hold
> 
> We can't do this as of now. We don't have an UBI based nodejs v18 image available without auth yet. [bugzilla.redhat.com/show_bug.cgi?id=2143885](https://bugzilla.redhat.com/show_bug.cgi?id=2143885)

I think we can still use the nodejs v16 version since its still supported. We can switch to v18 later when it becomes available. When I tried build and run it with v16 image it still worked fine.

**Comment by tumido** [comment]
Oh.. I didn't read the PR properly, you're not locking to v18 yet.... in that case we can proceed with this. The BZ was just resolved anyways so I'll work on updating node to v18 via separate PR.

**Review by tumido — APPROVED** [review]
/unhold
/lgtm
/approve

**Pull request merged**
