### PR TITLE
feat: Add proper error handler for k8s api

### PR DESCRIPTION
**Pull request by SamoKopecky**
Create a proper handler for the k8s API. [This](https://github.com/backstage/backstage/blob/master/packages/backend-common/src/middleware/errorHandler.ts) default backstage error handler makes sure the backend answers on errors.

### CODE REVIEW

**Review by tumido — CHANGES_REQUESTED** [review]
Hm. I think you're starting at the wrong end.

Yes, it's good to return a customized message if user is asking about a nonexistent cluster. But you should not generalize this for every 500 error. What if something went wrong elsewhere? 500 status code has a distinct meaning and the current server response totally makes sense - the server didn't expect the 500 error so it returns as much information as it possibly can gather...

This case looks more like: User is asking for a nonexistent resource. There's a status code for that which we should return: 404. Frontend should act upon that status code accordingly. It's not backend's job to assume availability status of a nonexistent resource. Maybe the resource exists but it's not configured in backstage properly. It's not the job of this plugin to presume this. Instead you should simply return a regular 404 message with a proper reason - this cluster doesn't exist in the config. Done. Let the frontend deal with it. Should it display cluster as "unavailable" or as "grayed out"? This should be handled on the frontend, not obscured by backend.

**Comment by SamoKopecky** [comment]
Thanks for the detailed explanation! I've tried to rework the whole error handling system based on your suggestions. I've tried to explain what I've done so its hopefully easier to understand the changes :slightly_smiling_face: . 

First of all I've restored the default error handler from backstage. This will be used only when all of the other error handling systems fail. I've created custom exceptions that later map to a json object similar to the default error handler json. More specifically the `name`, `message` and `statusCode` will be present in all responses in range of status codes 300-500. These custom exceptions are thrown in the code when an error situation arises for that exception.

I've also changed how the errors from the kubernetes api calls are handled ([here](https://github.com/SamoKopecky/service-catalog/blob/main/plugins/cluster-status-backend/src/statusCheck/StatusCheck.ts#L98-L107)). Since they don't get caught by the try/catch sequence (at least I didn't find a way to catch them), the returned `Promise` will get caught by a separate `catch` on the promise and create a similar looking json object to the default error handler.

Bellow I've listed some of the error situations.

Error before the backend even starts:
```bash
Backend failed to start up ServerConfigurationError: ACM cluster name wongly configured
    at StatusCheck.getAcmClusterFromConfig (webpack-internal:///../../plugins/cluster-status-backend/src/statusCheck/StatusCheck.ts:83:23)
    at new StatusCheck (webpack-internal:///../../plugins/cluster-status-backend/src/statusCheck/StatusCheck.ts:108:93)
    at createRouter (webpack-internal:///../../plugins/cluster-status-backend/src/service/router.ts:68:25)
    at createPlugin (webpack-internal:///./src/plugins/cluster-status.ts:8:103)
    at main (webpack-internal:///./src/index.ts:125:112) {
  type: 'server-configuration-error',
  statusCode: 500,
  description: 'the number of configured ACM clusters in the config file is\n' +
    '         (0) other than 1 , please contact the administrator'
}
```
Wrongly configured acm cluster token:
```json
{
  "error": {
    "name": "Unauthorized",
    "type": "acm-cluster-connection-error",
    "message": "Unauthorized"
  },
  "response": {
    "statusCode": 401
  }
}
```

Cluster name not found in config:
```json
{
  "error": {
    "name": "smauga cluster not found",
    "type": "cluster-not-found",
    "message": "smauga cluster is probably not contained in the config file"
  },
  "response": {
    "statusCode": 404
  }
}
```
Random unexpected error:
```json
{
  "error": {
    "name": "Error",
    "message": "random unexpected error",
    "level": "error",
    "service": "backstage",
  },
  "request": {
    "method": "GET",
    "url": "/status/smauga"
  },
  "response": {
    "statusCode": 500
  }
}
```

Let me know what you think!

**Review by tumido — CHANGES_REQUESTED** [review]
I think you're heading in the right direction here, but you should not invent new Error types or structures when the system already provides scaffolding to you. Take a look at following resources:

https://github.com/backstage/backstage/blob/master/packages/errors/src/errors/common.ts

https://github.com/backstage/backstage/blob/master/packages/errors/src/errors/CustomErrorBase.ts

https://github.com/backstage/backstage/blob/master/packages/errors/src/errors/ResponseError.ts

https://github.com/backstage/backstage/blob/master/packages/backend-common/src/middleware/errorHandler.ts

You don't need a new interface `ClusterError` and `ClusterStatusError` and `ServerConfigurationError`... You should be able to handle that via already available `NotFoundError` and `ResponseError` classes instead.

Instead of custom catches, rather make the handler throw the right exception and let the default error handler sort things out if possible. :slightly_smiling_face:

**Comment by SamoKopecky** [comment]
I've tried to utilize the default backstage errors to the maximum where I could, so all the basic errors are now handled with the backstage error handler. 
The situation with the ACM errors is a bit different and I am unsure of one thing:
- Since backstage is the client for ACM, I think we should always return code 500 on ACM errors and log the original error. If for example a token for infra cluster expires and a user tries to load a something that uses ACM, the response backstage receives is 404 Unauthorized, but for the user this information is useless since he can't do anything about it.

Also I am still working on the ACM error parsing since the response to an error is of type [HttpError](https://github.com/kubernetes-client/javascript/blob/master/src/gen/api/apis.ts#L119-L124) which can't be easily used in [ResponseError](https://github.com/backstage/backstage/blob/master/packages/errors/src/errors/ResponseError.ts) since the only way to create it is with the [fromResponse](https://github.com/backstage/backstage/blob/master/packages/errors/src/errors/ResponseError.ts) function which only takes in as an argument of type [ConsumedResponse](https://github.com/backstage/backstage/blob/master/packages/errors/src/errors/types.ts#L23-L43). I will try to parse the ACM error answer to a `ConsumedResponse` variable.

**Comment by tumido** [comment]
> Since backstage is the client for ACM, I think we should always return code 500 on ACM errors and log the original error.

I disagree. Always returning 500 Internal Server Error is really not helping anybody. It means you would treat all ACM errors the same. That should not be the case. Logging the original error doesn't help much since the end user doesn't have any access to logs.

>  If for example a token for infra cluster expires and a user tries to load a something that uses ACM, the response backstage receives is 404 Unauthorized, but for the user this information is useless since he can't do anything about it.

Do you mean 401 Unauthorized? I think this error is much more helpful than 500 which means that "something went wrong". If user reports that they are getting unauthorized on certain cluster it's more helpful than them reporting they are getting 500.

RHACM plugin is a mere proxy to kube api. We should passthrough the errors as they come, not play smart and obscure the original errors. Please raise 500 **only** when unforeseen error occures. This error code is reserved for such cases and shouldn't be intentionally raised when you know what caused the original error.

**Review by tumido — APPROVED** [review]
This looks so good! I like it!

/lgtm
/approve

**Pull request merged**
