### PR TITLE
feat: Prepare CI to build images

### LINKED ISSUE #62: Setup CI/CD for image builds on push to master
- [ ] Investigate if we can use AICoE-CI on push to main branch, if yes, set it up
- [ ] Copy over CI from https://github.com/operate-first/peribolos-as-a-service to test build images on PR and deliver new images on push

### PR DESCRIPTION
**Pull request by mimotej**
This PR creates Github actions CI which should on each push to main build image which is pushed to quay repository, it also runs tests on each PR

Part of: #62

### CODE REVIEW

**Comment by SamoKopecky** [comment]
@mimotej Can you please rebase this to `main`, the fix for the failing build is present on that branch.

**Comment by mimotej** [comment]
> @mimotej Can you please rebase this to `main`, the fix for the failing build is present on that branch.

Great thanks done :+1:

**Review by tumido — APPROVED** [review]
/lgtm
/approve

/hold

requires to populate QUAY credentials in the repository secrets.

**Comment by tumido** [comment]
secrets set, unholding

/unhold

**Pull request merged**
