### PR TITLE
feat: Install ADR plugin

### LINKED ISSUE #14: Plugin: Install and configure ADR viewer plugin
Install and configure ADR viewer

https://github.com/backstage/backstage/tree/master/plugins/adr

### PR DESCRIPTION
**Pull request by SamoKopecky**
Resolves #14 
- Add `ADR` page to catalog entities
- Add support for `ADRs` in search

image

### CODE REVIEW

**Comment by SamoKopecky** [comment]
Blocked by #34 
/hold

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Comment by tumido** [comment]
Unblocked, #34 merged
/unhold

**Comment by SamoKopecky** [comment]
Waiting for #38 to merge so that I can fix all merge all at once.

**Pull request merged**
