### PR TITLE
feat: Install security insights plugin

### LINKED ISSUE #17: Plugin: Install and configure Github security insights plugin
Surface Github security insights for componets.

https://roadie.io/backstage/plugins/security-insights/?utm_source=backstage.io&utm_medium=marketplace&utm_campaign=security-insights

### PR DESCRIPTION
**Pull request by SamoKopecky**
Resolves #17 

As mentioned in #34, if the insights are private and the user is not a member of an org, he won't be able to see the plugin information.
Here is an example of a repo that has security alerts https://github.com/skopecky-test/vulpy.

How it looks:

image
image

### CODE REVIEW

**Comment by SamoKopecky** [comment]
Blocked by #34 
/hold

**Comment by tumido** [comment]
Unblocked, #34 merged
/unhold

**Review by tumido — APPROVED** [review]
/lgtm

**Review by tumido — APPROVED** [review]
/lgtm

**Pull request merged**
